### ISSUE TITLE
Don't work in IOS

### ISSUE THREAD

**Issue by Alex-Kiosa** [sasan-salem/DummyBytes#3]
Hellow.
Thank for your job! But your solution doesn't work for IOS. When you click on the link, the file DummyBytes.php opens and nothing else happens. I have uploaded a video to demonstrate this - https://drive.google.com/file/d/1n7IObNy3DXxdlcO3ejuz2lI_9z6LdfcX/view?usp=sharing

**Comment by sasan-salem** [comment]
Hi. Thank you Alex.
As I mentened in title of tutorial (on Android devices), Unfortunately it doesn't work on the IOS. it works only on android devices. I tried to find a way but due to the IOS's limitations, the browser does not recognize the "file" concept and shows the bytes of the file in the browser. All you can do is detect the client's OS and if it was IOS, ask your client to use an external browser.

**Comment by Alex-Kiosa** [comment]
Sasan thanks for your feedback.
I did not notice that this solution is only for android. I apologize for the carelessness.
